version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: Backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: Frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    depends_on:
      - backend
